metrics/prometheus.go
metrics/prometheus_test.go

Hi!
First of all I really like the idea for the project you are building here, and thank you for doing that!  
While browsing through the source code I noticed that you could be some additional parts of `prometheus` repo to  make the integration more straight forward. I added the use of `promauto` since it is way too easy to forget the call to register.
I also added the `testutil` package for unit tests to be more explicit with checking the metric value. 
Let me know what you think of the changes.

Using promauto to initialize the metric and testutil in tests

---

store/redis.go
store/redis_test.go

I found during my end-to-end test using a real redis db that the redis client is returning strings, not bytes. The tag functionality was not working because of this.

Fix redis tags: redis client is returning strings

---

go.mod
go.sum
store/ristretto.go
store/ristretto_test.go
test/mocks/store/clients/ristretto_interface.go

In version v0.0.2 Sets with TTL functionality was added to ristretto. It would be very helpful to support it in gocache.

feat: support ristretto TTL eviction

---

marshaler/marshaler.go
store/bigcache.go
store/bigcache_test.go

When faillback from Redis to Bigcache:  type of the value from Redis is string, set to Bigcache will cause panic, see #70.
According to the code from [marshaler](https://github.com/eko/gocache/blob/master/marshaler/marshaler.go#L28-L34), I made the same change to Bigcache store.

fix: fallback from redis to bigcache will panic

---

README.md

Hi there. `gocache` is a really handy library. But when I used it with the redis storage for the first time, it took me a while to figure out how to deal with the case when the key does not exist. I think it may be better to add some examples to the README, and here it is.

docs(readme): add descriptions about how to deal with the returned error from the redis storage

---

README.md
store/bigcache.go
store/bigcache_bench_test.go
store/go_cache.go
store/interface.go
store/memcache.go
store/memcache_bench_test.go
store/options.go
store/options_test.go
store/pegasus.go
store/pegasus_bench_test.go
store/pegasus_test.go
store/redis.go
store/redis_bench_test.go
store/redis_test.go
store/rediscluster.go
store/rediscluster_bench_test.go
store/rediscluster_test.go
store/ristretto.go

**Fix** cacheManager use redis/redis-cluster/pegasus with document that cause by context parameter:
**Fixed result**:
**Local test result**:
[gocache_local_test.txt](https://github.com/eko/gocache/files/6411105/gocache_local_test.txt)

fix: fix cacheManager use error with redis and pegasus

---

cache/loadable.go
go.mod
go.sum
store/memcache.go
store/memcache_test.go
test/mocks/cache/cache_interface.go
test/mocks/codec/codec_interface.go
test/mocks/metrics/metrics_interface.go
test/mocks/store/clients/bigcache_interface.go
test/mocks/store/clients/freecache_interface.go
test/mocks/store/clients/go_cache_interface.go
test/mocks/store/clients/memcache_interface.go
test/mocks/store/clients/redis_interface.go
test/mocks/store/clients/rediscluster_interface.go
test/mocks/store/clients/ristretto_interface.go
test/mocks/store/store_interface.go

Summary
- Updates memcached setTags method to use CompareAndSwap to update existing items to avoid overwriting other clients. And uses Add to create new tag keys.
- Adds Close method to LoadableCache to stop setter goroutine

Fix Race Condition in Memcached Store, Close Loadable to Stop Setter Routine

---

README.md

Hello,
I was having a quick look at this repository and noticed that #76 added support for [patrickmn/go-cache](https://github.com/patrickmn/go-cache) but the README was not mentionning it.
This PR fixes adds go-cache to list of supported caches and a small usage example.
Cheers

Add patrickmn/go-cache to README

---

cache/cache.go
cache/cache_test.go

*Feature request*
Especially when using the LoadableCache, you would typically provide the arguments of the loadFunc as a key and inside the cache the key would be generated as the md5 checksum of the type and value when the key is not already a string. I would like the keys to be human readable and thus implement my owner type to string conversion.
With this PR the user is able to implent it's own `GetCacheKey()` function when required. The only BC break I see is when an existing user already implemented this function and wasn't expeciting it to be used by the cache to generate the cache key.

feat: Support for a key that would implement it's own key generator

---

store/go_cache.go
store/go_cache_test.go

Concurrency issues are hard to catch, but the tests that I've written fail in the exact right way at my computer.
This change is already tested in concurrent environment, works safely.

Make setTags method concurrency-safe

---

cache/chain.go
cache/chain_test.go

messed up https://github.com/eko/gocache/pull/140 here is a rebased version with corrections asked for.

chain set to run set on all cache stores

---

store/bigcache.go
store/bigcache_test.go
store/go_cache.go
store/go_cache_test.go
store/memcache.go
store/memcache_test.go
store/pegasus.go
store/ristretto.go
store/ristretto_test.go

@eko what do you think, should we delete the collection of cache keys after each of the keys was deleted?

Delete cache item containing cache keys for a tag upon tag invalidation

---

store/options.go
store/options_test.go

I assume this was just an oversight. I was expecting that any specified options would override defaults, but unspecified options would still use the default options.
IE:
```go
// Given
defaultOptions := &Options{
expiration: 25 * time.Second,
}
// When
options := applyOptionsWithDefault(defaultOptions, WithCost(7))
// Then
assert.Equal(t, int64(7), options.cost)
assert.Equal(t, 25*time.Second, options.expiration)
```

Fix for applyOptionsWithDefault not keeping unmodified options

---

lib/store/options.go
store/rueidis/rueidis.go
store/rueidis/rueidis_bench_test.go
store/rueidis/rueidis_test.go

Hey @eko , thanks for doing that and sorry for taking so long to include the tests.
I'm adding a new test for NotFound, just to ensure it is working as intended. Also, fixing the idea of the `clientExpiration` option I've done in the previous proposal. The idea here is to keep the `expiration` using TTL (server-side), but give an option to the user to use a different expiration time for the server-assisted client cache (more info on the link below).
Adding [ClientSideCacheExpiration](https://github.com/rueian/rueidis#client-side-caching) option for [rueidis](https://github.com/rueian/rueidis), tweaking tests and benchmarks.
```
goos: linux
goarch: amd64
pkg: github.com/eko/gocache/v4/store/rueidis
cpu: AMD Ryzen 5 1600 Six-Core Processor            
BenchmarkRueidisSet …
```

Fixing Rueidis store implementation

---

store/bigcache/bigcache.go
store/bigcache/bigcache_test.go

Problem and solution presented in issue #172.
The bigcache implementation of GetWithTTL is just a hard coded 0 duration but with no indication in API it will not work as intended.
I suggest instead returning an error that lets the user know that the method is in fact not supported and it should not be relied upon.

Mark bigcache GetWithTTL as not implemented

---

README.md
store/hazelcast/hazelcast.go
store/hazelcast/hazelcast_benchmark_test.go
store/hazelcast/hazelcast_test.go

It is better to have `HazelcastMapInterfaceProvider` in order to get a new map instance every time when it is needed.

Hazelcast store refactoring

---

README.md

The `"github.com/eko/gocache/lib/v4/generic"` import is redundant.

docs(readme): remove redundant generic import

---

lib/go.mod
lib/go.sum
lib/marshaler/marshaler.go
lib/marshaler/marshaler_test.go

`msgpack` is now using modules as of `v5`+, this PR upgrades the library to the latest version v5.3.5. From the [changelog](https://github.com/vmihailenco/msgpack/blob/v5/CHANGELOG.md#535-2021-10-22), there are a few breaking changes, however, none of them affect the usage of the library here.

build: upgrade github.com/vmihailenco/msgpack to v5

---

lib/cache/metric.go
lib/cache/metric_test.go

metrics are not initialized when creating a new MetricCache, so they don't appear in prometheus until the first `Get` call
I've updated the test cases to reflect on this change

Initialize metrics on MetricCache creation

---

lib/store/options.go
store/ristretto/ristretto.go
store/ristretto/ristretto_bench_test.go
store/ristretto/ristretto_mock.go
store/ristretto/ristretto_test.go

Add configurable option to ristretto cache store to be able to wait/blocks until all buffered writes have been applied. 
ref: https://github.com/dgraph-io/ristretto/blob/main/cache.go#L219
Fixes : #207

[Ristretto Store] Add configurable synchronous write option

---

lib/cache/loadable.go
lib/cache/loadable_test.go
lib/go.mod
lib/go.sum

used https://pkg.go.dev/golang.org/x/sync/singleflight to avoid parallel running of the loading function.
modified test to check the new behavior

avoid parallel running a load function for the same key #242

---

README.md
store/hazelcast/hazelcast.go
store/hazelcast/hazelcast_benchmark_test.go
store/hazelcast/hazelcast_test.go

After I got some insight into the Hazelcast client, I reconsidered the changes applied in #203. Creating a new Hazelcast map instance for each operation does not offer any benefits. Instead, we can safely use a single map instance for all operations, making the API clearer and more concise.

Create Hazelcast store from map instance

---

store/redis/redis_test.go

Hacktoberfest
- Increase unit test lib/store/redis from 80.4% to 97.1%

add unit test for lib/store/redis

---

store/memcache/memcache.go
store/memcache/memcache_test.go

according to the godoc of github.com/bradfitz/gomemcache at https://pkg.go.dev/github.com/bradfitz/gomemcache/memcache both `Get` and `Delete` may return a `memcache.ErrCacheMiss` when the key is not found. This should be reflected with a `NotFound` error for a `Get` or no error for a `Delete`.
Used https://github.com/daangn/minimemcached to test this.

memcached: fix Delete and Get for missing items

---

lib/cache/loadable.go
lib/cache/loadable_test.go

fix(loadable): cache value in setChannel

---

lib/cache/chain.go
lib/cache/chain_test.go

Improvements to error handling:
* [`lib/cache/chain.go`](diffhunk://#diff-1c9bd527f5aa84131bfaf0887a142b434117515f5609e3453b61b839a7cfce38L81-R84): Modified the error formatting to use `%w` for wrapping errors and simplified the error aggregation by using `errors.Join`.
It will allow us to handle the underlying errors returned by `Set`.

fix: improve error handling in ChainCache.Set method

---

store/bigcache/bigcache.go
store/bigcache/bigcache_test.go

- Just proxy through to Get() with a static TTL
- Needed to support the ChainCache use-case

Add GetWithTTL() support to Bigcache store to fix ChainCache

---

lib/codec/codec.go
store/rediscluster/rediscluster.go

chore: fix some comments

---

store/hazelcast/hazelcast.go
store/hazelcast/hazelcast_test.go

It modifies the handling of tag TTLs in the Hazelcast store to use the newly introduced `TagsTTL` option from #276

feat: add TTL support for tags in Hazelcast store

---

store/pegasus/go.mod
store/redis/redis.go

It requires `go 1.23.0` after bumping `x/net` to `0.38.0` in #285
Fixes the error in CI workflow.
https://github.com/eko/gocache/actions/runs/14546559416/job/40812732156#step:4:20

Fix pegasus module version

---

store/rueidis/rueidis.go

Method GetWithTTL from rueidis driver uses CacheTTL() method on rueidis result, which returns **client side** cache TTL value, which not actually interesting in Redis store scenario.
This PR uses TTL command to retrieve actual TTL value from Redis.

Return true TTL value in rueidis driver

---

lib/metrics/prometheus.go
lib/metrics/prometheus_test.go

Resolves https://github.com/eko/gocache/issues/288
This PR adds an attribute namespace option for Prometheus metrics.
It's empty by default so it guarantees backward compatibility.

add attributes namespaces option for prometheus metrics
